Variorum JSON API.
LLNL/variorum pull request #133
Opened 2020-08-01 20:43 UTC by tpatki

Please see the commits for detailed information on the source code.
Sphinx documentation to follow as a separate PR that explains how to use the API correctly, describes the assumptions made from a vendor-neutrality point of view, and expected output.

2020-08-08 13:41 UTC, rountree approved these changes

2020-08-10 17:06 UTC, slabasan commented on src/examples/CMakeLists.txt
> +    variorum-json-get-node-power-example
Can we move `-json-` to `-json-example`? I think it'll help with the sorting of the examples.

2020-08-10 17:06 UTC, slabasan requested changes
+1

2020-08-13 23:22 UTC, tpatki commented
@slabasan Thanks for the comment. API has been changed to `variorum_get_node_power_json`, and should be consistent now,  and has been tested on Quartz/Lassen. Travis is green :)

2020-08-15 23:14 UTC, merged