Moves variorum_log to an environment variable.
LLNL/variorum pull request #270
Opened 2022-06-27 18:28 UTC by chaz-browne

# Description

Please provide a short summary of the change and tag any issues being fixed. Please also include relevant motivation and context. List any
dependencies that may be required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please provide hardware architecture specs and instructions so we can reproduce.

- [ ] Test A: Hardware architecture, machine name, example/test run
- [ ] Test B: Hardware architecture, machine name, example/test run
- [ ] ...

# Checklist:

- [ ] I have run `./scripts/check-code-format.sh` and confirm my code follows the style guidelines of variorum
- [ ] I have added comments in my code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass with my changes

        
Thank you for taking the time to contribute to Variorum!

2022-06-27 19:11 UTC, tpatki commented
@chaz-browne @rountree : 

Build fails with a missing `string.h` in some files. I could find at least one place (IvyBridge files) where it needs to be added, there may be other files where you need to include `string.h`. 

Also, in many places I think you have a copy-paste error. For instance, on Skylake nodes, the build fails with:

```
/home/runner/work/variorum/variorum/src/variorum/Intel/Skylake_55.c:427:35: error: ordered comparison of pointer with integer zero [-Werror=extra]
[364](https://github.com/LLNL/variorum/runs/7079250509?check_suite_focus=true#step:5:365)
     if(val != NULL && getenv(val) > 0){ 
```

I think you meant to check for `if (val != NULL && strlen(val) > 0)` -- not an `getenv(val) > 0`. `Getenv` returns a `char*` so you can't make an integer based comparison. 

-----

You also put the closing brace for the `fm_06_4f_get_node_power_json(json_t *get_power_obj)` in Broadwell_4F.c in the wrong place, leaving a stray call to `json_get_power_data` outside the function. 

-----

You have a  similar error here, where the call to `son_get_power_domain_info(get_domain_obj, msrs.msr_pkg_power_info,` was deleted incorrectly when adding `VARIOUM_LOG`.
https://github.com/LLNL/variorum/pull/270/files#diff-9eb8cb80e2412cc9674989480c818658b0cefc7e5545c5229ecd4a859161494aL440

https://github.com/LLNL/variorum/pull/270/files#diff-9eb8cb80e2412cc9674989480c818658b0cefc7e5545c5229ecd4a859161494aR442

There may be a few others that I haven't caught.

----
Also, as a general note:  before submitting any PRs, please run `run scripts/check-code-format.sh` so it formats your code correctly and doesn't fail.

2022-06-27 19:16 UTC, tpatki requested changes

2022-06-27 19:16 UTC, tpatki commented on src/variorum/Intel/IvyBridge_3E.c
> +    if (val != NULL && strlen(val) > 0)
Add string.h header for this file.

2022-06-27 19:16 UTC, tpatki commented on src/variorum/Intel/Skylake_55.c
> +    if (val != NULL && getenv(val) > 0)
Should be `strlen(val) > 0`

2022-06-27 19:16 UTC, tpatki commented on src/variorum/Intel/Skylake_55.c
> +    if (val != NULL && getenv(val) > 0)
Should be `strlen(val) > 0`

2022-06-27 19:16 UTC, tpatki commented on src/variorum/Intel/Skylake_55.c
> +    if (val != NULL && getenv(val) > 0)
Should be strlen(val) > 0

2022-06-27 19:16 UTC, tpatki commented on src/variorum/Intel/Skylake_55.c
> +    if (val != NULL && getenv(val) > 0)
Should be strlen(val) > 0

2022-06-27 19:16 UTC, tpatki commented on src/variorum/Intel/Skylake_55.c
> +    if (val != NULL && getenv(val) > 0)
This happens in many places in this file, please fix.

2022-06-27 19:16 UTC, tpatki commented on src/variorum/Intel/Broadwell_4F.c
> +    msrs.msr_rapl_power_unit, msrs.msr_pkg_power_limit;
Incorrectly deleted the original call to ` json_get_power_domain_info`, stray arguments left behind.

2022-06-27 19:48 UTC, rountree commented
@tpatki Thanks!

@chaz-browne Did you compile and run each of the examples?  If they did (and they worked fine) then we might have a git issue.

2022-06-27 19:58 UTC, tpatki commented
Please test the PR on: 

- [ ] Comus (Broadwell), 
- [ ] Thompson (Haswell), 
- [ ] Alehouse (Power9)
- [ ] Rhetoric (Skylake, single socket)
- [ ] ARM Juno r2
- [ ] Lassen with the CUDA host-config file build for NVML testing (different than alehouse).

These are the ones we have available. I wish we could also test actively on AMD and other Intel micro-architectures.

2022-06-27 22:42 UTC, rountree commented
@tpatki Testing across those architectures goes beyond what I was hoping to do here.  I had intended this PR to get command line parsing into `getopt()` and fix the existing help messages (e.g., `--help` was mentioned but often not supported).

I think it would be valuable to add architecture-specific messages to the `-h` output, but I think that's a separate PR.

If you'd like to see that feature go in this summer I'm sure @chaz-browne can handle it, at which point this becomes a question of bookkeeping.

Thoughts?

2022-07-15 02:23 UTC, tpatki commented
@slabasan Why aren't CI checks triggered automatically on this PR? I couldn't find the option to start CI tests either...I must be missing something simple here.

2022-07-15 03:23 UTC, slabasan commented
Going to re-open a new PR in hopes CI launches

2022-07-25 02:16 UTC, rountree commented
I'm working on it....

2022-07-26 02:07 UTC, tpatki commented
@slabasan @rountree I rebased and resolved some conflicts here, but this is not ready to merge as we need to update the VARIORUM_LOG part in the new AMD GPU port that was merged today. I will get to it tonight or tomorrow.

2022-07-26 03:59 UTC, tpatki commented
Ugh, I think I messed something up in the rebase. Sorry. Fixing now.

@slabasan @rountree

2022-07-28 02:46 UTC, tpatki commented
@rountree @slabasan @chaz-browne 

I found a problem when testing, Stephanie and I will fix it tomorrow -- don't worry about it. 

Just documenting it here, so we remember to fix this and test it on all known architectures. 

Basically, you are not checking for the value of VARIORUM_LOG, you are only checking for its length to be greater than zero. That means, if someone sets that variable to `0`, it will still print the log enter and exit msgs, which should not be the case. For example, see the result below from the CUDA build on Lassen:

```
[patki1@lassen88:examples]$ export VARIORUM_LOG=0

[patki1@lassen88:examples]$ ./variorum-print-power-example 
_LOG_VARIORUM_ENTER:/g/g90/patki1/src/var-clean/chaz/variorum/src/variorum/variorum.c:variorum_print_power::598
Running volta_get_power
_NVIDIA_GPU_POWER_USAGE Host Socket DeviceID Power_W
_NVIDIA_GPU_POWER_USAGE lassen88 0 0 34.807002
_NVIDIA_GPU_POWER_USAGE lassen88 0 1 35.787002
_NVIDIA_GPU_POWER_USAGE lassen88 1 2 36.768002
_NVIDIA_GPU_POWER_USAGE lassen88 1 3 35.810002
_LOG_VARIORUM_EXIT:/g/g90/patki1/src/var-clean/chaz/variorum/src/variorum/variorum.c:variorum_print_power::618
_LOG_VARIORUM_ENTER:/g/g90/patki1/src/var-clean/chaz/variorum/src/variorum/variorum.c:variorum_print_power::598
Running volta_get_power
_NVIDIA_GPU_POWER_USAGE lassen88 0 0 35.297002
_NVIDIA_GPU_POWER_USAGE lassen88 0 1 35.787002
_NVIDIA_GPU_POWER_USAGE lassen88 1 2 36.768002
_NVIDIA_GPU_POWER_USAGE lassen88 1 3 35.810002
_LOG_VARIORUM_EXIT:/g/g90/patki1/src/var-clean/chaz/variorum/src/variorum/variorum.c:variorum_print_power::618
```

It should be checking for `if (val != NULL && atoi(*val) > 0)`  or something like that instead of `if (val != NULL && strlen(val) > 0)`, which is what you currently have. 


ToDo: Test the PR build on:

- [ ]  Comus (Broadwell),
- [ ]   Thompson (Haswell),
- [ ]   Alehouse (Power9)
- [ ]   Rhetoric (Skylake, single socket)
- [ ]   ARM Juno r2
- [ ]   Corona AMG GPU
- [ ]   Lassen with the CUDA host-config file build for NVML testing (different than alehouse)

.

2022-07-28 19:37 UTC, tpatki submitted a review, later dismissed
LGTM

2022-07-28 19:51 UTC, slabasan approved these changes

2022-07-28 19:51 UTC, merged