Parse and plot powmon power data #415
LLNL/variorum pull request #423
Opened 2023-06-08 16:50 UTC by altahat2003

This script plots power data of `powmon`.

2023-06-08 16:53 UTC, tpatki commented
Hi @altahat2003 : thank you for this! Somehow it looks like you didn't see the PR template. Can you run the `scripts/check-code-format.sh` and push up the reformatted file, so the code is formatted correctly?

2023-06-08 20:04 UTC, tpatki commented
Hi @altahat2003 LGTM! I'm going to test once at my end to get a feel for it, and then merge. I think it can go in v0.7 -- thank you for your help with this useful script!

2023-06-08 20:10 UTC, altahat2003 commented
Hi @tpatki, thanks for your help and guidance to get my first PR submitted successfully :)

2023-06-08 21:33 UTC, tpatki requested changes

2023-06-08 21:33 UTC, tpatki commented on src/powmon/scripts/powmon-plot.py
> +#
Add the `-d description` flag here.

2023-06-08 21:33 UTC, tpatki commented on src/powmon/scripts/powmon-plot.py
> +        help="Output directory path. If not defined, plots will be saved in the input path.",
I believe this sets the title, pleas correct the help message here.

2023-06-08 21:59 UTC, tpatki commented on src/powmon/scripts/powmon-plot.py
> +#   python3 plotting.py [options]
Name should be `powmon-plot.py`

2023-06-08 22:00 UTC, tpatki commented on src/powmon/scripts/powmon-plot.py
> +    parser = argparse.ArgumentParser(prog="plotting", description="Plotting Power Data")
`prog="powmon_plot"` here.

2023-06-08 22:48 UTC, altahat2003 commented on src/powmon/scripts/powmon-plot.py
> +    parser = argparse.ArgumentParser(prog="plotting", description="Plotting Power Data")
It has been updated!

2023-06-09 00:07 UTC, tpatki approved these changes, later dismissed

2023-06-09 00:46 UTC, tpatki commented
@slabasan @altahat2003 

Two finals thing left for this PR (updating here in case I'm not around tomorrow, also see slack). 
- [ ] Add a check for python3.8 and print out an error if it is an earlier version.
- [ ] Fix x-axis on aggregated plot


I've tested it thoroughly on Lassen otherwise, and it looks good. Mostly ready to go, I think it's good to add it to v0.7 if we can get it all done in time today. If not, feel free to push it out to v0.8. 

One known issue is when GPU/Mem power is reported as -1 (eg on Quartz or Tioga), the plot data may look messed up in that case. This isn't a problem with the script, but rather with data being unavailable on some platforms. We can handle this issue later by just not plotting data that has -1 (or aggregated negative) values, I can open a bug fix, should be quick to update.

2023-06-12 18:29 UTC, slabasan approved these changes

2023-06-12 18:29 UTC, merged